###################  项目启动端口  ###################
server:
  port: 80
  
###################  spring配置  ###################
spring:
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: classpath:/WEB-INF/view/
  http:
    converters:
      preferred-json-mapper: fastjson
    multipart:
      max-request-size: 100MB #最大请求大小
      max-file-size: 100MB #最大文件大小
  aop:
    proxy-target-class: true #false为启用jdk默认动态代理,true为cglib动态代理
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/shequ?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: 12345
    db-name: shequ
    filters: log4j,wall,mergeStat
  freemarker:
    cache: false #启用模板缓存
    prefix:   #前缀名
    suffix: .ftl  #后缀名
    content-type: text/html
    charset: UTF-8 #编码格式
    request-context-attribute: request  #req访问request
    expose-request-attributes: true
    expose-session-attributes: true
    template-loader-path: classpath:/WEB-INF/view/ #模板加载路径 按需配置
    settings:
      template_update_delay: 1
      default_encoding: UTF-8
      number_format: '0.##'   #数字格式化，无小数点
      classic_compatible: true
      template_exception_handler: ignore
      
logging:
  level.root: info
  level.com.zhang.shequ: debug
  path: logs/
  file: shequ.log

###################  mybatis-plus配置  ###################
mybatis-plus:
  mapper-locations: classpath*:com/zhang/shequ/core/mapper/mapping/*.xml
  typeAliasesPackage: com.zhang.shequ.core.entity
  global-config:
    id-type: 0  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true
    logic-delete-value: 0
    logic-not-delete-value: 1
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  configuration:
    map-underscore-to-camel-case: false
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用
  